### PR TITLE
fix(ssh): support ed25519 SSH keys

### PR DESCRIPTION
**Pull request by seanknox**
Updated the SSH parser regex to allow for [ed25519 SSH keys](http://ed25519.cr.yp.to/). Also added (very simple) test for key that would fail the regex. 

I develop in other languages but this is the very first golang code I've ever written, so very open to any nits you may have.

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
Do the controller and builder support ed25519 keys?

**Comment by seanknox** [comment]
@Joshua-Anderson AFAICT they do; I added additional controller testing in https://github.com/deis/controller/pull/1109 to help answer that question in the future. builder uses [crypto/ssh](https://godoc.org/golang.org/x/crypto/ssh#PublicKey) which supports Ed25519.

**Comment by Joshua-Anderson** [comment]
Cool! It looks like this has some minor linter problems:

```
Manadatory Linters: These must pass
pkg/ssh/ssh_test.go:1::warning: file is not gofmted with -s (gofmt)
Optional Linters: These should pass
pkg/ssh/ssh_test.go:24:9:warning: range var keyAndId should be keyAndID (golint)
pkg/ssh/ssh_test.go:43:9:warning: range var keyAndId should be keyAndID (golint)
```

You can run `make test-style` to run them locally

**Comment by seanknox** [comment]
Fixed—thanks for the heads up.

**Pull request merged**
