### PR TITLE
fix(logger): Split on the double new lines when printing log messages

### PR DESCRIPTION
**Pull request by jchauncey**

### CODE REVIEW

**Comment by bacongobbler** [comment]
I just made an identical change in my client as well. `deis logs` is parsed nicely again. I'll file an issue for the butt-ugly response data that the client has to parse, though.

**Comment by krancour** [comment]
@jchauncey can you just reference whatever controller change this complements?

**Comment by bacongobbler** [comment]
No controller changes required. The root issue is https://github.com/deis/workflow/issues/202 so this works around that response from the controller. In my port of https://github.com/deis/controller/pull/592 from v1 the expected HTTP response was not the same as we expected.

**Comment by mboersma** [comment]
```
--- FAIL: TestAppsLogs (0.01s)
	apps_test.go:370: Expected test foo bar, Got "test foo bar"
	apps_test.go:370: Expected test, Got "test"
```

**Comment by bacongobbler** [comment]
@jchauncey would you mind fixing up the unit tests?

**Comment by jchauncey** [comment]
yeah didnt realize they would break

**Pull request merged**
