### PR TITLE
feat(CI): upload CLI to seperate buckets

### PR DESCRIPTION
**Pull request by Joshua-Anderson**
To avoid making changes, I'm going to start by uploading to both the `workflow-cli` bucket and then specific bucket. We can then start to migrate.

@vdice how do you propose looking up a revision for a CLI between the PR and master bucket in e2e? Try to download from master, and if that fails download from the PR bucket?

### CODE REVIEW

**Comment by bacongobbler** [comment]
is there an issue open to explain why this change is necessary? My concern is how this will affect the usability of install-v2.sh to install specific versions of the client

**Comment by bacongobbler** [comment]
fwiw I'm all for this just wanna know some background :)

**Comment by Joshua-Anderson** [comment]
@bacongobbler there's a few reasons for the change.

1. security: We have credentials injected into PR builds, so making sure there is no way for a PR to touch/overwrite the offical binaries is nice. A edge case in our new versioning system accidentally overwrote the v2.4.0 artifacts, but a malicious attack could do far more harm.
2. Cleanness: We want to keep the master and release binaries indefinitely, but many PR binaries are only used for CI. This makes it much easier to just clean up PR artifacts every once in a while.

> My concern is how this will affect the usability of install-v2.sh to install specific versions of the client

We'll mirror the release binaries from the `workflow-cli` bucket to the `workflow-cli-release` bucket and then change the url in the install script. It should be transparent to users. If anyone uses the GCS URL directly, we can leave the workflow-cli bucket unchanged for a while.

**Comment by vdice** [comment]
> @vdice how do you propose looking up a revision for a CLI between the PR and master bucket in e2e? Try to download from master, and if that fails download from the PR bucket?

@Joshua-Anderson that does sound like a first approach.  Otherwise, if we can send down a flag (`IS_PR` or some such) from the initial Jenkins test job all the way down to the workflow-e2e container which could be used to determine the bucket to attempt pulling from.

**Pull request merged**
