### PR TITLE
feat(Makefile): set docker build flags via environment variable

### PR DESCRIPTION
**Pull request by mboersma**

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
I don't know the full context behind this, but it will have a significant impact on development time for `make test`... from seconds to several minutes.

**Comment by mboersma** [comment]
@Joshua-Anderson it's true, which is why we've avoided doing this for so long, but building with cached Docker layers just means once in a while a bug is hidden and you don't discover it until later. In this case, switching the base image from `ubuntu-slim` to `ubuntu` broke a `gunzip` command for most images, but we didn't notice until building locally because a later Docker image layer was already cached in CI.

For developers, you can get the old behavior with:
```
DOCKER_BUILD_FLAGS= make docker-build
```

**Comment by mboersma** [comment]
See this comment https://github.com/deis/postgres/pull/180#issuecomment-273562141 for more details.

**Comment by vdice** [comment]
@mboersma when you get a chance, can you amend the commit and push again to kick of a fresh CI run?

**Comment by mboersma** [comment]
Jenkins, test this please.

**Pull request merged**
