### PR TITLE
fix(whitelist): format the deis whitelist properly

### PR DESCRIPTION
**Pull request by kmala**

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
Is this still  targeted for the 2.5 release?

**Comment by kmala** [comment]
i would want it if possible but will check with @mboersma and @bacongobbler as they are doing release and fine with moving to next release as it is just an UX issue.

**Comment by ultimateboy** [comment]
Before
```bash
$ deis whitelist:list
=== taller-addendum Whitelisted Addresses1.2.3.4
```
after
```bash
$ deis whitelist:list
=== taller-addendum Whitelisted Addresses
1.2.3.4
```

**Comment by bacongobbler** [comment]
let's cut a v2.5.1.

**Pull request merged**
