### PR TITLE
feat(git): add more flags to the git command

### LINKED ISSUE #39: Make the `git:remote` command print out the remote's value even if the remote already exists
Currently, the output looks like this:

```console
ENG000656:k8s-claimer aaronschlesinger$ deis git:remote
fatal: remote deis already exists.
Error: exit status 128
```

Would be nicer if it printed out what the remote should be, but it could still exit non-zero

### PR DESCRIPTION
**Pull request by Joshua-Anderson**
Requires workflow-e2e#278
Fixes #39

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
This CI is going to fail because it requires deis/workflow-e2e#278, which has passes using the binaries from this PR.

**Comment by vdice** [comment]
@Joshua-Anderson I see what looks like new scenarios/logic added in this PR that aren't covered in the required workflow-e2e PR (https://github.com/deis/workflow-e2e/pull/278).  Can we wrap any added logic under test?  (Or is it already covered?)

**Comment by Joshua-Anderson** [comment]
I was thinking that since they were cli-only, they didn't really belong in workflow-e2e. If we were to implement component specific functional tests, they would belong there.

I was unsure of whether to add the logic to e2e or just pass on it for now. I'm happy to either.

**Comment by vdice** [comment]
@Joshua-Anderson I'd say, if the anticipated timeline for introducing functional tests is a ways out, we create ticket(s) to add minimal specs in workflow-e2e covering logic added here.  Otherwise, perhaps a note can be added to the initial ticket(s) around the functional testing initiative?  All this is assuming unit tests don't apply here...

Barring all of that, should this PR be manually tested?

**Comment by Joshua-Anderson** [comment]
I could write unit tests, but they would be tricky because nearly all of the PR deals with calling the git cli and reading the output.

It seems like a good approach for now could be to write e2e tests and then if we end up writing functions tests remove them.

**Comment by Joshua-Anderson** [comment]
I added some basic e2e tests to cover the `git:remote` functionality.

**Pull request merged**
