### PR TITLE
feat(cmd): add auth:whoami --all

### LINKED ISSUE #54: implement auth:whoami
see deis/controller#543

### PR DESCRIPTION
**Pull request by bacongobbler**
closes #54 
supercedes #118

### CODE REVIEW

**Comment by bacongobbler** [comment]
Ah, I think the reason why it's failing to build is because my PR was out of date with master and had an older Jenkinsfile. That should do it!

**Comment by bacongobbler** [comment]
Hmm, nope that didn't do the trick. @vdice am I missing something here to make the PR build with deis/controller-sdk-go#36?

**Comment by vdice** [comment]
@bacongobbler We don't yet have the mechanism in place for 'Requires' between workflow-cli and controller-sdk-go.  As of this writing, a PR in controller-sdk-go is run thru e2e by using that version in an otherwise 'master' version of workflow-cli, and, likewise, a PR in workflow-cli just defaults to using the 'master' version of controller-sdk-go.  

That being said, we should be in a good position to add the 'Requires' functionality for any PRs in the former case (controller-sdk-go).  We should be able to clone into a forked workflow-cli repo at a certain commit before building the binary with the controller-sdk-go commit.  I will create this ticket.

**Comment by bacongobbler** [comment]
Adding both LGTM labels as SDK, controller and e2e `auth:whoami` PRs have been approved for merge, so I'm assuming this is fine as well.

**Pull request merged**
