### PR TITLE
Fix link to troubleshooting doc

### PR DESCRIPTION
**Pull request by seanknox**
Hiya, the Troubleshooting URL was pointing to the wrong place.

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
Wow, this has been overlooked (along with most of our other contributing documents) for some time!

To reduce maintenance burden (and forgetting to update them, as happened here 😄), I belive we're now pointing people to out main contributing document at https://github.com/deis/workflow/blob/master/CONTRIBUTING.md

How does something like:
```markdown
# Contributing to Deis

This project is part of Deis. You can find the latest contribution
guidelines [in the main Workflow repository](https://github.com/deis/workflow/blob/master/CONTRIBUTING.md).
```

sound to you as a replacement for this current contributing document?

**Comment by seanknox** [comment]
Sounds good to me!

**Comment by Joshua-Anderson** [comment]
Would you like to update this PR with a new contributing document? If you're busy it's not a big deal, and I'll be happy to make the update.

**Comment by seanknox** [comment]
@Joshua-Anderson Used the text as you suggested.

**Pull request merged**
