### PR TITLE
feat(Makefile): add git branch and sha information to the uploaded blob

### PR DESCRIPTION
**Pull request by helgi**
https://cloud.google.com/storage/docs/gsutil/addlhelp/WorkingWithObjectMetadata?hl=en_US#custom-metadata

### CODE REVIEW

**Comment by slack** [comment]
Some unique job identifier would be amazing.

**Comment by helgi** [comment]
Any ideas what that could be in Jenkins? @jchauncey do you know of any good ones ? I could make it `env.BUILD_URL` which basically just links back to the overall job, name, id and all that. Thoughts?

**Comment by helgi** [comment]
Decided to go wild, `JOB_NAME`, `BUILD_NUMER` and `BUILD_URL` - At this point more information is better

**Comment by helgi** [comment]
```
docker run --rm -v /home/jenkins/workspace/Deis/workflow-cli/PR-177/gopath/src/github.com/deis/workflow-cli/tmp:/.config -v /home/jenkins/workspace/Deis/workflow-cli/PR-177/gopath/src/github.com/deis/workflow-cli/_dist:/upload google/cloud-sdk:latest gsutil -mq -h x-goog-meta-git-branch:remotes/origin/pr/177 -h x-goog-meta-git-sha:47def285be17a4fe8b8ffd6b758e82a9bd948e0a -h x-goog-meta-ci-job:Deis/workflow-cli/PR-177 -h x-goog-meta-ci-number:8 -h x-goog-meta-ci-url:https://ci.deis.io/job/Deis/job/workflow-cli/job/PR-177/8/ cp -a public-read -r /upload/* gs://workflow-cli
```

A bit repetitive since the BUILD_URL has the whole shebang in it but whatever. Going with this

**Pull request merged**
